defaults:
  - _self_
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 8
action_repeat: 1
discount: 0.99
temporal_ensemble: true
action_sequence: 4
# train settings
num_seed_frames: 0
# eval
eval_every_frames: 2500
num_eval_episodes: 10
# snapshot
save_snapshot: false
save_policy_every_frames: 25000
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4 #4
nstep: 1
batch_size: 256
demo_batch_size: 256
use_relabeling: true
# misc
seed: 1
device: cuda
save_video: false #true
save_train_video: false
use_tb: false
use_wandb: true
# experiment
experiment: exp
# agent
lr: 5e-5
weight_decay: 0.1
feature_dim: 64
num_update_steps: 1
use_compile: false

episode_length: 600
num_train_frames: 1000000
num_demos: 120
camera_keys: ["rgb"]
dataset_root: /datasets/demonstrations_downscaled_reseted_env_84x84 #${hydra:runtime.cwd}/../demonstrations_downscaled
stone_height_threshold: 1.5
camera_shape: [84, 84]
task_name: AgxCave-Rock-Capturing-Vision-v0
reward_type: sparse
state_based_only: true #false

agent:
  _target_: agx_src.cqn_as.CQNASAgent
  rgb_obs_shape: ??? # to be specified later
  low_dim_obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: cuda #${device}
  lr: ${lr}
  weight_decay: ${weight_decay}
  critic_target_tau: 0.02
  critic_target_interval: 1
  update_every_steps: 1
  num_expl_steps: 0
  feature_dim: ${feature_dim}
  hidden_dim: 512
  levels: 3
  bins: 5
  atoms: 51
  gru_layers: 1
  rgb_encoder_layers: 0 #0
  use_parallel_impl: true #false  # useful in powerful GPUs
  v_min: -10.0 #changed from -2.0 to match negative reward setup # maybe -1.0/1.0?
  v_max: 2.0
  critic_lambda: 0.1
  stddev_schedule: 0.01
  bc_lambda: 1.0
  bc_margin: 0.01
  state_based_only: ${state_based_only}

wandb:
  project: cqn
  entity: ujvjm-karlsruhe-institute-of-technology
  name: test-run

hydra:
  run:
    dir: ./exp_local/cqn_as_agx/${now:%Y%m%d%H%M%S}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  # launcher:
  #   timeout_min: 430000 #4300
  #   cpus_per_task: 5
  #   gpus_per_node: 1
  #   tasks_per_node: 1
  #   mem_gb: 120
  #   nodes: 1
  #   submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
